// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5Z3u96iirvJKTx3alTlYbzLENZMNXn_s',
    appId: '1:1010600879077:web:f9c8b283e47a5da206050c',
    messagingSenderId: '1010600879077',
    projectId: 'growtogether-9f1b8',
    authDomain: 'growtogether-9f1b8.firebaseapp.com',
    storageBucket: 'growtogether-9f1b8.firebasestorage.app',
    measurementId: 'G-ZGHT4EY3MD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFBZKhyvRe7XAHvmQ5EGs_frfiHsT8r5U',
    appId: '1:1010600879077:android:4a8423ab9c3e654306050c',
    messagingSenderId: '1010600879077',
    projectId: 'growtogether-9f1b8',
    storageBucket: 'growtogether-9f1b8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNezQ70A8pckabEyLceCanz22VdCAbT8M',
    appId: '1:1010600879077:ios:857d424e06a7b7e606050c',
    messagingSenderId: '1010600879077',
    projectId: 'growtogether-9f1b8',
    storageBucket: 'growtogether-9f1b8.firebasestorage.app',
    iosBundleId: 'com.example.growtogetherUx',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNezQ70A8pckabEyLceCanz22VdCAbT8M',
    appId: '1:1010600879077:ios:857d424e06a7b7e606050c',
    messagingSenderId: '1010600879077',
    projectId: 'growtogether-9f1b8',
    storageBucket: 'growtogether-9f1b8.firebasestorage.app',
    iosBundleId: 'com.example.growtogetherUx',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC5Z3u96iirvJKTx3alTlYbzLENZMNXn_s',
    appId: '1:1010600879077:web:c1af124d01d8ffb106050c',
    messagingSenderId: '1010600879077',
    projectId: 'growtogether-9f1b8',
    authDomain: 'growtogether-9f1b8.firebaseapp.com',
    storageBucket: 'growtogether-9f1b8.firebasestorage.app',
    measurementId: 'G-FHFPECMXDL',
  );
}
